# App of Apps
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd  # ArgoCD's namespace
  # dependency, lowest priorty will be created first
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/iam-vanimina/mysql-argocd.git 
    targetRevision: main   # or a tag/commit hash
    path: .       # folder in repo with Kubernetes YAMLs
    helm:
      releaseName: mysql
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: roboshop
<<<<<<< HEAD
    #namespace: argocd
=======
>>>>>>> 86b383d931ca27953d7acff16b5096241f68c1b7
  syncPolicy:
    automated:
      prune: true           # delete resources not in Git
      selfHeal: true        # revert out-of-band changes
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
