---
# Source: mysql/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: roboshop
  labels:
    app: mysql
    project: roboshop
    tier: db
spec:
  clusterIP: None
  selector:
    app: mysql
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306
---
# Source: mysql/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    project: roboshop
    tier: db
spec:
  selector:
    app: mysql
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306
---
# Source: mysql/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    matchLabels:
      app: mysql
      project: roboshop
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "mysql-headless"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mysql
        project: roboshop
        tier: db # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: vanimina/mysql:1.2.0
        env:
        - name: MYSQL_DATABASE
          valueFrom:
           secretKeyRef:
             name: cities-db-secret
             key: MYSQL_DATABASE

        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: cities-db-secret
              key: MYSQL_USER

        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
              name: cities-db-secret
              key: MYSQL_ROOT_PASSWORD        

        - name: MYSQL_PASSWORD
          valueFrom:
             secretKeyRef:
              name: cities-db-secret
              key: MYSQL_PASSWORD    
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
      
  # Instead of creating a PVC resource, you can directly provide in statefulset
  volumeClaimTemplates:
  - metadata:
      name: mysql
      namespace: roboshop
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: 
      
      resources:
        requests:
          storage: 4Gi
